# Frontend
- alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: dark_teal

# Sunrise
- alias: Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: light.turn_off
    entity_id: light.sonoff_1000950368_2

# Sunset
- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: light.turn_on
    entity_id: group.sunset_lights

# PiHole
- alias: Enable Pihole
  trigger:
    - platform: state
      entity_id: input_select.pihole_time
      to: 'Enabled'
  action:
    - service: pi_hole.enable

- alias: Disable Pihole
  trigger:
    - platform: state
      entity_id: input_select.pihole_time
      to: 'Disabled'
  action:
    - service: pi_hole.disable
      data:
        duration: '00:00:00'

- alias: Disable Pihole for 15 seconds
  trigger:
    - platform: state
      entity_id: input_select.pihole_time
      to: '0.15'
  action:
    - service: pi_hole.disable
      data:
        duration: '00:00:15'

- alias: Disable Pihole for 1 minute
  trigger:
    - platform: state
      entity_id: input_select.pihole_time
      to: '1'
  action:
    - service: pi_hole.disable
      data:
        duration: '00:01:00'

- alias: Disable Pihole for 5 minutes
  trigger:
    - platform: state
      entity_id: input_select.pihole_time
      to: '5'
  action:
    - service: pi_hole.disable
      data:
        duration: '00:05:00'
