# Frontend
- alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: dark_teal

# Sunrise
- alias: Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: light.turn_off
    entity_id: light.sonoff_1000950368_2

# Sunset
- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: light.turn_on
    entity_id: group.sunset_lights

# Water boiler
- alias: Turn on water boiler
  trigger:
    - platform: time
      at:
        - '06:00:00'
        - '19:00:00'
    - platform: state
      entity_id: input_boolean.wb_ignore_trigger
      to: 'on'
    - platform: state
      entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
        state: 'off'
      - condition: state
        entity_id: input_boolean.wb_ignore_melaja
        state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_10008508fb

- alias: Turn off water boiler
  trigger:
    - platform: numeric_state
      entity_id: sensor.termotanque_temperatura
      above: 28
    - platform: state
      entity_id: switch.sonoff_10008508fb
      to: 'on'
    - platform: state
      entity_id: input_boolean.wb_ignore_trigger
      to: 'off'
  condition:
    - condition: numeric_state
      entity_id: sensor.termotanque_temperatura
      above: 28
    - condition: state
      entity_id: input_boolean.wb_ignore_trigger
      state: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.sonoff_10008508fb

# PiHole
- alias: Enable Pihole again
  trigger:
    - platform: state
      entity_id: sensor.pihole_status
      to: 'Enabled'
  condition:
    - condition: state
      entity_id: switch.pihole
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.pihole

# AC's Condensate Pump
- alias: Turn on condensate pump
  trigger:
    - platform: state
      entity_id: climate.living_ac
      to:
        - 'cool'
        - 'heat'
        - 'dry'
    - platform: state
      entity_id: climate.dormitorio_ac
      to:
        - 'cool'
        - 'heat'
        - 'heat_cool'
        - 'dry'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_1000854c6a

- alias: Turn off condensate pump living
  trigger:
    - platform: state
      entity_id: climate.living_ac
      to: 'off'
  condition:
    - condition: state
      entity_id: climate.dormitorio_ac
      state: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.sonoff_1000854c6a

- alias: Turn off condensate pump dormitorio
  trigger:
    - platform: state
      entity_id: climate.dormitorio_ac
      to: 'off'
  condition:
    - condition: state
      entity_id: climate.living_ac
      state: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.sonoff_1000854c6a

# Calendar
- alias: Turn on lights at Shabbat veIom Tov
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  action:
    service: light.turn_on
    entity_id:
      - light.sonoff_1000950368_1
      - light.sonoff_100094ff53_2
      - light.sonoff_1000951aac
