---

sun:
system_health:

http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

lovelace:
  mode: yaml
  dashboards:
    lovelace-extension:
      mode: yaml
      filename: views/extension.yaml
      title: false
      show_in_sidebar: false
  resources:
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module
      url: /hacsfiles/lovelace-state-switch/state-switch.js
    - type: module
      url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    - type: module
      url: /hacsfiles/simple-thermostat/simple-thermostat.js
    - type: module
      url: /hacsfiles/vacuum-card/vacuum-card.js
    - type: module
      url: /hacsfiles/lovelace-card-mod/card-mod.js
    - type: module
      url: /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js

frontend:
  themes: !include_dir_merge_named themes

panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-timeline-variant
    url: !secret iframe_grafana
  pihole:
    title: Pi-hole
    icon: mdi:pi-hole
    url: !secret iframe_pihole

panel_custom:
  - name: panel-redirect
    url_path: redirect-server-controls
    sidebar_title: Server Controls
    sidebar_icon: mdi:server
    module_url: /local/panel-redirect.js
    config:
      target: /config/server_control

google_assistant:
  project_id: !secret google_projectid
  service_account: !include google_service_account.json
  report_state: false
  exposed_domains:
    - switch
    - light
    - climate
    - fan
  entity_config: !include config/google_assistant_entities.yaml

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    base_url: !secret http_base_url
    service_name: google_say

group: !include config/groups.yaml
automation: !include_dir_merge_list automations/
sensor: !include config/sensors.yaml
script: !include_dir_merge_named scripts/
input_select: !include config/input_select.yaml
input_text: !include config/input_text.yaml
input_number: !include config/input_number.yaml
input_boolean: !include config/input_boolean.yaml
switch: !include config/switch.yaml
light: !include config/light.yaml

binary_sensor:
  - platform: workday
    country: AR
    add_holidays:
      - '2021-05-24'
      - '2021-06-21'
      - '2021-08-16'
      - '2021-10-11'
      - '2021-11-22'
    remove_holidays:
      - '2021-06-17'
      - '2021-08-17'
      - '2021-10-12'

mobile_app:
ios:
  actions: !include config/ios_actions.yaml

homeassistant:
  external_url: !secret http_base_url
  time_zone: America/Argentina/Buenos_Aires
  unit_system: metric
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  elevation: !secret ha_ele
  auth_mfa_modules:
    - type: totp
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

influxdb:
  exclude:
    entity_globs: "*"
  include:
    entities: !include config/influxdb_entities.yaml

jewish_calendar:
  language: english
  diaspora: true
  havdalah_minutes_after_sunset: 50

hacs:
  token: !secret hacs_token
  sidepanel_icon: mdi:alpha-c-box

ambient_station:
  api_key: !secret ambient_station_api_key
  app_key: !secret ambient_station_app_key

accuweather:
  api_key: !secret accuweather_api_key
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  name: Home

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  reload: always
  scan_interval: '00:01:00'
  devices: !include config/sonoff_devices.yaml

smartir:

climate:
  - platform: smartir
    name: Living
    unique_id: living_ac
    device_code: 2000
    controller_data: remote.living_remote
    temperature_sensor: sensor.lu7and_inside_temp
    humidity_sensor: sensor.lu7and_humidity_in
    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Dormitorio
    unique_id: dormitorio_ac
    device_code: 1400
    controller_data: remote.bedroom_remote
    temperature_sensor: sensor.dormitorio_temperatura
    humidity_sensor: sensor.dormitorio_humidity
    power_sensor: binary_sensor.ac_power

media_player:
  - platform: smartir
    name: Living TV
    unique_id: living_tv
    device_code: 1020
    controller_data: remote.living_remote
    power_sensor: binary_sensor.tv_power
  - platform: smartir
    name: Bedroom TV
    unique_id: bedroom_tv
    device_code: 1020
    controller_data: remote.bedroom_remote
    power_sensor: binary_sensor.tv_power

rest_command:
  hue:
    url: "{{ states('input_text.hue_url') }}/{{ resource }}/{{ name }}/{{ 'action' if (resource=='groups') else 'state' }}"
    method: PUT
    payload: "{{ payload }}"

shell_command:
  apt_upgrade: "sudo apt upgrade --yes"

notify:
  - platform: file
    name: file
    filename: !secret file_path

recorder:
  commit_interval: 60
  include:
    entities:
      - sensor.termotanque_temperatura

history:
  include:
    entities:
      - sensor.termotanque_temperatura

logger:
  default: critical
  logs:
    homeassistant.bootstrap: info
    homeassistant.config: info
    homeassistant.util.package: info
    homeassistant.setup: error
    homeassistant.components: warning
