
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  server_host: 127.0.0.1
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/custom-header/custom-header.js
    - type: js
      url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    - type: module
      url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    - type: js
      url: /hacsfiles/fan-control-entity-row/fan-control-entity-row.js
    - type: module
      url: /hacsfiles/lovelace-layout-card/layout-card.js
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module
      url: /hacsfiles/lovelace-state-switch/state-switch.js
    - type: module
      url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    - type: module
      url: /hacsfiles/atomic-calendar-revive/atomic-calendar-revive.js

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
input_select: !include input_select.yaml

mobile_app:
ios:
  actions: !include ios_actions.yaml

homeassistant:
  external_url: !secret http_base_url
  time_zone: America/Argentina/Buenos_Aires
  unit_system: metric
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  elevation: !secret ha_ele
  auth_mfa_modules:
    - type: totp

google:
  client_id: !secret google_client
  client_secret: !secret google_secret

jewish_calendar:
  language: english
  diaspora: true
  havdalah_minutes_after_sunset: 50

hacs:
  token: !secret hacs_token
  sidepanel_icon: mdi:alpha-c-box

ambient_station:
  api_key: !secret ambient_station_api_key
  app_key: !secret ambient_station_app_key

accuweather:
  api_key: !secret accuweather_api_key
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  name: Home

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  reload: always
  devices:
    1000766c93:
      device_class: light
      name: Lampara pie
    1000770cc7:
      device_class: light
      name: Lampara mesa de luz
    10008504ad:
      device_class: light
      name: Luz pasillo
    1000950368:
      device_class: [ light, light ]
      name: Living
    100094ff53:
      device_class: [ light, light ]
      name: Cocina
    1000951aac:
      device_class: light
      name: Bano
    1000951b70:
      device_class: light
      name: Deposito

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 54
  platform: smart_life

pi_hole:
  - host: '127.0.0.1:8080'
    api_key: !secret pihole_token

spotify:
  client_id: !secret spotify_client
  client_secret: !secret spotify_secret

remote:
  - platform: broadlink
    host: !secret living_rm2_ip
    mac: !secret living_rm2_mac
    name: living
  - platform: broadlink
    host: !secret dormitorio_rm2_ip
    mac: !secret dormitorio_rm2_mac
    name: dormitorio

smartir:

climate:
  - platform: smartir
    name: Living
    unique_id: living_ac
    device_code: 2000
    controller_data: remote.living_remote
    temperature_sensor: sensor.lu7and_inside_temp
    humidity_sensor: sensor.lu7and_humidity_in
    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Dormitorio
    unique_id: dormitorio_ac
    device_code: 1400
    controller_data: remote.bedroom_remote
    temperature_sensor: sensor.dormitorio_temperatura
    humidity_sensor: sensor.dormitorio_humidity
    power_sensor: binary_sensor.ac_power

input_boolean:
  blank:
    icon: 'mdi:'
  blank_chart:
    icon: 'mdi:chart-line'
  wb_ignore_trigger:
    name: Ignore auto trigger
    initial: off
  wb_ignore_melaja:
    name: Ignore melaja sensor
    initial: off
  pending_kiddush_levanah:
    name: Pending Kiddush Levanah
    icon: mdi:moon-waning-gibbous

input_number:
  volume_speaker:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
    initial: 0.45

# Easy way to query secrets from template
input_text:
  latitude:
    initial: !secret ha_lat
  longitude:
    initial: !secret ha_lon
  utc_offset:
    initial: !secret offset
  ipgeolocation_token:
    initial: !secret ipgeolocation_token

# Speedtest.net against Movistar
speedtestdotnet:
  server_id: 7696
  scan_interval:
    minutes: 75

logger:
  default: info
