
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module
      url: /hacsfiles/lovelace-state-switch/state-switch.js
    - type: module
      url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    - type: module
      url: /hacsfiles/simple-thermostat/simple-thermostat.js
    - type: module
      url: /hacsfiles/vacuum-card/vacuum-card.js
    - type: module
      url: /hacsfiles/lovelace-card-mod/card-mod.js

frontend:
  themes: !include_dir_merge_named themes

panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:chart-line
    url: !secret iframe_grafana
  pihole:
    title: Pi-hole
    icon: mdi:pi-hole
    url: !secret iframe_pihole

google_assistant:
  project_id: !secret google_projectid
  service_account: !include google_service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - climate
    - fan
  entity_config: !include config/google_assistant_entities.yaml

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    base_url: !secret http_base_url
    service_name: google_say

group: !include config/groups.yaml
automation: !include config/automations.yaml
sensor: !include config/sensors.yaml
script: !include config/scripts.yaml
input_select: !include config/input_select.yaml
input_text: !include config/input_text.yaml
input_number: !include config/input_number.yaml
input_boolean: !include config/input_boolean.yaml
switch: !include config/switch.yaml

mobile_app:
ios:
  actions: !include config/ios_actions.yaml

homeassistant:
  external_url: !secret http_base_url
  time_zone: America/Argentina/Buenos_Aires
  unit_system: metric
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  elevation: !secret ha_ele
  auth_mfa_modules:
    - type: totp
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

influxdb:
  exclude:
    entity_globs: "*"
  include:
    entities: !include config/influxdb_entities.yaml

jewish_calendar:
  language: english
  diaspora: true
  havdalah_minutes_after_sunset: 50

hacs:
  token: !secret hacs_token
  sidepanel_icon: mdi:alpha-c-box

ambient_station:
  api_key: !secret ambient_station_api_key
  app_key: !secret ambient_station_app_key

accuweather:
  api_key: !secret accuweather_api_key
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  name: Home

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  reload: always
  scan_interval: '00:01:00'
  devices: !include config/sonoff_devices.yaml

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 54
  platform: smart_life

pi_hole:
  - host: '127.0.0.1:8080'
    api_key: !secret pihole_token

smartir:

climate:
  - platform: smartir
    name: Living
    unique_id: living_ac
    device_code: 2000
    controller_data: remote.living_remote
    temperature_sensor: sensor.lu7and_inside_temp
    humidity_sensor: sensor.lu7and_humidity_in
    power_sensor: binary_sensor.ac_power
  - platform: smartir
    name: Dormitorio
    unique_id: dormitorio_ac
    device_code: 1400
    controller_data: remote.bedroom_remote
    temperature_sensor: sensor.dormitorio_temperatura
    humidity_sensor: sensor.dormitorio_humidity
    power_sensor: binary_sensor.ac_power

media_player:
  - platform: smartir
    name: Living TV
    unique_id: living_tv
    device_code: 1020
    controller_data: remote.living_remote
    power_sensor: binary_sensor.tv_power
  - platform: smartir
    name: Bedroom TV
    unique_id: bedroom_tv
    device_code: 1020
    controller_data: remote.bedroom_remote
    power_sensor: binary_sensor.tv_power

vacuum:
  - platform: xiaomi_miio
    name: Vacuum
    host: !secret vacuum_ip
    token: !secret vacuum_token

light:
  - platform: group
    name: Living
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
      - light.hue_color_lamp_4
  - platform: group
    name: Bedroom
    entities:
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2
  - platform: switch
    name: Outdoor
    entity_id: switch.sonoff_100076dd3e

rest_command:
  hue:
    url: "{{ states('input_text.hue_url') }}/{{ resource }}/{{ name }}/{{ 'action' if (resource=='groups') else 'state' }}"
    method: PUT
    payload: "{{ payload }}"

logger:
  default: critical
