- platform: template
  sensors:
    dormitorio_temperatura:
      friendly_name: Temperatura dormitorio
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_10008504ad', 'temperature') }}"
    dormitorio_humedad:
      friendly_name: Humedad dormitorio
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_10008504ad', 'humidity') }}"
    termotanque_temperatura:
      friendly_name: Temperatura termotanque
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_10008508fb', 'temperature') }}"
    termotanque_humedad:
      friendly_name: Humedad termotanque
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_10008508fb', 'humidity') }}"

- platform: command_line
  name: PiHole Status
  command: curl -X GET 'http://127.0.0.1:8080/admin/api.php?status'
  value_template: >
    {{ value_json.status }}

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) }}'
