# RSPi status
# https://www.home-assistant.io/integrations/systemmonitor/
- platform: systemmonitor
  resources:
    - type: last_boot
    - type: processor_use
    - type: memory_use_percent
    - type: memory_use
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /var/log
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: process
      arg: lighttpd
    - type: process
      arg: pihole-FTL

- platform: command_line
  name: Uptime
  command: "uptime | sed -n 's/.*up \\([^,]*\\),.*/\\1/p'"
  scan_interval: 43200

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: Raspbian packages
  scan_interval: 900
  command: "/usr/lib/nagios/plugins/check_apt | sed -n 's/.*upgrades=\\([^;]*\\);.*/\\1/p'"
  unit_of_measurement: "pending update(s)"

# HA
- platform: version
  name: Current
  source: local

- platform: version
  name: Latest
  source: pypi

- platform: cert_expiry
  host: !secret host

# eWeLink Sonoff TH16
- platform: template
  sensors:
    dormitorio_temperatura:
      friendly_name: Temperatura dormitorio
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('light.sonoff_10008504ad', 'temperature') | round(1) }}"
    dormitorio_humedad:
      friendly_name: Humedad dormitorio
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('light.sonoff_10008504ad', 'humidity') }}"
    cocina_temperatura:
      friendly_name: Temperatura cocina
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_100085067c', 'temperature') | round(1) }}"
    cocina_humedad:
      friendly_name: Humedad cocina
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_100085067c', 'humidity') }}"
    termotanque_temperatura:
      friendly_name: Temperatura termotanque
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_10008508fb', 'temperature') | round(1) }}"
    termotanque_humedad:
      friendly_name: Humedad termotanque
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_10008508fb', 'humidity') }}"
    deposito_temperatura:
      friendly_name: Temperatura deposito
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_100085069c', 'temperature') | round(1) }}"
    deposito_humedad:
      friendly_name: Humedad deposito
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_100085069c', 'humidity') }}"

# PiHole
# https://github.com/pi-hole/AdminLTE/blob/master/api.php
- platform: rest
  name: PiHole status
  resource: "http://127.0.0.1:8080/admin/api.php?status"
  scan_interval: 3
  value_template: >
    {{ value_json.status | capitalize }}

- platform: rest
  name: PiHole versions
  resource: "http://127.0.0.1:8080/admin/api.php?versions"
  json_attributes:
    - core_branch
    - core_current
    - core_latest
    - core_update
    - web_branch
    - web_current
    - web_latest
    - web_update
    - FTL_branch
    - FTL_current
    - FTL_latest
    - FTL_update
  value_template: "OK"
- platform: template
  sensors:
    pihole_core_current:
      value_template: "{{ state_attr('sensor.pihole_versions', 'core_current') | replace('v','') }}"
    pihole_core_latest:
      value_template: "{{ state_attr('sensor.pihole_versions', 'core_latest') | replace('v','') }}"
    pihole_web_current:
      value_template: "{{ state_attr('sensor.pihole_versions', 'web_current') | replace('v','') }}"
    pihole_web_latest:
      value_template: "{{ state_attr('sensor.pihole_versions', 'web_latest') | replace('v','') }}"
    pihole_ftl_current:
      value_template: "{{ state_attr('sensor.pihole_versions', 'FTL_current') | replace('v','') }}"
    pihole_ftl_latest:
      value_template: "{{ state_attr('sensor.pihole_versions', 'FTL_latest') | replace('v','') }}"

# Github
- platform: github
  access_token: !secret hacs_token
  repositories:
    - path: 'RetroPie/RetroPie-Setup'

- platform: template
  sensors:
    retropie_setup_latest:
      friendly_name: RetroPie
      value_template: "{{ state_attr('sensor.retropie_setup', 'latest_release_tag') }}"

# Tokens as sensor
- platform: template
  sensors:
    living_rm2_ip:
      value_template: !secret living_rm2_ip
    dormitorio_rm2_ip:
      value_template: !secret dormitorio_rm2_ip

# Date
# Sunrise & Moonrise API: https://api.met.no/weatherapi/sunrise/2.0/documentation
- platform: moon

- platform: template
  sensors:
    sun_elevation:
      friendly_name: Sun elevation
      unit_of_measurement: "deg"
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"

- platform: rest
  name: Moon elevation
  resource_template: "https://api.met.no/weatherapi/sunrise/2.0/.json?lat={{ states('input_text.latitude') }}&lon={{ states('input_text.longitude') }}&date={{ now().strftime('%Y-%m-%d') }}&offset={{ states('input_text.utc_offset') }}"
  unit_of_measurement: "deg"
  value_template: "{{ value_json.location.time[0].moonposition.elevation | round(2) }}"
