# RSPi status
# https://www.home-assistant.io/integrations/systemmonitor/
- platform: systemmonitor
  resources:
    - type: last_boot
    - type: processor_use
    - type: memory_use_percent
    - type: memory_use
    - type: disk_use_percent
      arg: /
    - type: disk_use_percent
      arg: /var/log
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: process
      arg: pihole-FTL

- platform: command_line
  name: Uptime
  command: "uptime | sed -n 's/.*up \\([^,]*\\),.*/\\1/p'"
  scan_interval: 43200

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: System Updates
  scan_interval: 900
  command: "/usr/lib/nagios/plugins/check_apt | sed -n 's/.*upgrades=\\([^;]*\\);.*/\\1/p'"

- platform: template
  sensors:
    pending_updates:
      friendly_name: Pending updates
      value_template: "Raspbian: {{ states.sensor.system_updates.state }}, HACS: {{ states.sensor.hacs.state}}"

# eWeLink Sonoff TH16
- platform: template
  sensors:
    dormitorio_temperatura:
      friendly_name: Temperatura dormitorio
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_10008504ad', 'temperature') | float }}"
    dormitorio_humedad:
      friendly_name: Humedad dormitorio
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_10008504ad', 'humidity') | float }}"
    cocina_temperatura:
      friendly_name: Temperatura cocina
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_100085067c', 'temperature') | float }}"
    cocina_humedad:
      friendly_name: Humedad cocina
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_100085067c', 'humidity') | float }}"
    termotanque_temperatura:
      friendly_name: Temperatura termotanque
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_10008508fb', 'temperature') | float }}"
    termotanque_humedad:
      friendly_name: Humedad termotanque
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_10008508fb', 'humidity') | float}}"
    deposito_temperatura:
      friendly_name: Temperatura deposito
      device_class: temperature
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('switch.sonoff_100085069c', 'temperature') | float }}"
    deposito_humedad:
      friendly_name: Humedad deposito
      device_class: humidity
      unit_of_measurement: '%'
      value_template: "{{ state_attr('switch.sonoff_100085069c', 'humidity') | float}}"

# PiHole
# https://github.com/pi-hole/AdminLTE/blob/master/api.php
- platform: rest
  name: PiHole status
  resource: "http://127.0.0.1:8080/admin/api.php?status"
  value_template: >
    {{ value_json.status }}

- platform: rest
  name: PiHole versions
  resource: "http://127.0.0.1:8080/admin/api.php?versions"
  json_attributes:
    - core_branch
    - core_current
    - core_latest
    - core_update
    - web_branch
    - web_current
    - web_latest
    - web_update
    - FTL_branch
    - FTL_current
    - FTL_latest
    - FTL_update
  value_template: "OK"
- platform: template
  sensors:
    pihole_core_update:
      friendly_name: Pi-Hole core update
      value_template: "{% if states.sensor.pihole_versions.attributes['core_update'] == true %}1{% else %}0{% endif %} pending"
    pihole_web_update:
      friendly_name: Pi-Hole web update
      value_template: "{% if states.sensor.pihole_versions.attributes['web_update'] == true %}1{% else %}0{% endif %} pending"
    pihole_ftl_update:
      friendly_name: Pi-Hole FTL update
      value_template: "{% if states.sensor.pihole_versions.attributes['FTL_update'] == true %}1{% else %}0{% endif %} pending"

# Tokens as sensor
- platform: template
  sensors:
    living_rm2_ip:
      value_template: !secret living_rm2_ip
    dormitorio_rm2_ip:
      value_template: !secret dormitorio_rm2_ip
