title: Home

# Button Card Templates configuration
# https://github.com/custom-cards/button-card#configuration
button_card_templates:
  rounded:
    styles:
      card:
       - border-radius: 50px
       - height: 55px
       - width: 55px
       - box-shadow: none
      icon:
       - width: 60%
  custom_icon_name:
    layout: icon_name
    styles:
      card:
      - font-size: 100%
      - height: 45px
      icon:
       - width: 50%
  custom_tv_button:
    styles:
      card:
        - height: 59px
  divider:
    styles:
      card:
        - height: 10px

views:
  - !include views/home.yaml
  - !include views/calendar/main.yaml
  - !include views/media.yaml
  - !include views/sys.yaml
  - !include views/stateon.yaml
