title: Home

# Custom header configuration
# https://maykar.github.io/custom-header/#configuration/main
custom_header:
  compact_mode: true
  hide_help: true
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        disable_sidebar: true
        footer_mode: true
        hide_config: true
        options_hide: true

# Button Card Templates configuration
# https://github.com/custom-cards/button-card#configuration
button_card_templates:
  rounded:
    styles:
      card:
       - border-radius: 100px
      icon:
       - width: 40%
  divider:
    styles:
      card:
        - height: 40px

resources:
  - type: module
    url: /hacsfiles/custom-header/custom-header.js
  - type: js
    url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
  - type: js
    url: /hacsfiles/fan-control-entity-row/fan-control-entity-row.js
  - type: module
    url: /hacsfiles/lovelace-layout-card/layout-card.js
  - type: module
    url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /hacsfiles/button-card/button-card.js
  - type: module
    url: /hacsfiles/lovelace-card-mod/card-mod.js
  - type: module
    url: /hacsfiles/lovelace-state-switch/state-switch.js

views:
  - !include lovelace/home.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/ac.yaml
  - !include lovelace/tv/main.yaml
  - !include lovelace/graph.yaml
