title: Home
custom_header: !include lovelace/cards/custom_header.yaml

resources:
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: js
    url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /community_plugin/circle-sensor-card/circle-sensor-card.js
  - type: js
    url: /community_plugin/fan-control-entity-row/fan-control-entity-row.js
  - type: module
    url: /hacsfiles/lovelace-layout-card/layout-card.js
  - type: module
    url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /hacsfiles/button-card/button-card.js
  - type: module
    url: /hacsfiles/lovelace-card-mod/card-mod.js
  - type: module
    url: /hacsfiles/lovelace-state-switch/state-switch.js

views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/lights.yaml
  - !include lovelace/views/ac.yaml
  - !include lovelace/views/tv.yaml
  - !include lovelace/views/graph.yaml
