title: Home

# Custom header configuration
# https://maykar.github.io/custom-header/#configuration/main
custom_header:
  compact_mode: true
  hide_help: true
  exceptions:
    - conditions:
        media_query: "(max-width: 375px)"
      config:
        disable_sidebar: true
        footer_mode: true
        hide_config: true
        options_hide: true

# Button Card Templates configuration
# https://github.com/custom-cards/button-card#configuration
button_card_templates:
  rounded:
    styles:
      card:
       - border-radius: 100px
      icon:
       - width: 40%
  divider:
    styles:
      card:
        - height: 40px

views:
  - !include lovelace/home.yaml
  - !include lovelace/lights.yaml
  - !include lovelace/ac.yaml
  - !include lovelace/tv/main.yaml
  - !include lovelace/wb.yaml
  - !include lovelace/pihole.yaml
  # Graphs
  - !include lovelace/graph/rspi_memory.yaml
  - !include lovelace/graph/ws_temp.yaml
  - !include lovelace/graph/ws_humidity.yaml
  - !include lovelace/graph/net_traffic.yaml
  - !include lovelace/graph/net_throughput.yaml
  - !include lovelace/graph/net_packets.yaml
  - !include lovelace/graph/net_speedtest.yaml
