title: Home

# Custom header configuration
# https://maykar.github.io/custom-header/#configuration/main
custom_header:
  compact_mode: true
  hide_help: true
  exceptions:
    - conditions:
        media_query: "(max-width: 375px)"
      config:
        disable_sidebar: true
        footer_mode: true
        hide_config: true
        options_hide: true

# Button Card Templates configuration
# https://github.com/custom-cards/button-card#configuration
button_card_templates:
  rounded:
    styles:
      card:
       - border-radius: 50px
       - height: 55px
       - width: 55px
       - box-shadow: none
      icon:
       - width: 60%
  custom_icon_name:
    layout: icon_name
    styles:
      card:
      - font-size: 100%
      icon:
       - width: 35%
  divider:
    styles:
      card:
        - height: 10px

views:
  - !include views/home.yaml
  - !include views/lights.yaml
  - !include views/ac.yaml
  - !include views/tv/main.yaml
  - !include views/wb.yaml
  - !include views/pihole.yaml
  # Graphs
  - !include views/graph/rspi_memory.yaml
  - !include views/graph/ws_temp.yaml
  - !include views/graph/ws_humidity.yaml
  - !include views/graph/net_traffic.yaml
  - !include views/graph/net_throughput.yaml
  - !include views/graph/net_packets.yaml
  - !include views/graph/net_speedtest.yaml
