---

# Browser extension (305992)
path: main
views:

  - cards:
      - type: entities
        show_header_toggle: false
        entities:

          - type: call-service
            name: Turn off all but outside light
            icon: mdi:lightbulb-multiple-off
            service: script.turn_on
            service_data:
              entity_id: script.turn_off_but_outside

          - type: call-service
            name: Toggle basic lights
            icon: mdi:lightbulb-multiple
            service: light.toggle
            service_data:
              entity_id: group.basic_lights

          - switch.climate_living

          - switch.climate_bedroom

          - entity: switch.sonoff_1000950368_2
            name: Office
            icon: mdi:air-conditioner
