# https://www.home-assistant.io/integrations/google_assistant/#configuration

# Ignore
# ------

# iFan03
fan.bedroom_fan:
  expose: false
fan.dormitorio:
  expose: false
light.sonoff_1000954850_1:
  expose: false
# POW
switch.sonoff_1000854c6a:
  expose: false
# TH16 kitchen
switch.sonoff_100085067c:
  expose: false
# Dual 1/2
switch.sonoff_100091d007_1:
  expose: false
# Dual 2/2
switch.sonoff_100091d007_2:
  expose: false
# Hue lights
light.hue_color_lamp_1:
  expose: false
light.hue_color_lamp_2:
  expose: false
light.hue_color_lamp_3:
  expose: false
light.hue_color_lamp_4:
  expose: false
light.hue_white_lamp_1:
  expose: false
light.hue_white_lamp_2:
  expose: false
light.living_2:
  expose: false
light.bedroom_2:
  expose: false
# Misc
switch.pihole:
  expose: false
switch.media_player_speaker:
  expose: false
# Unavailable
switch.sonoff_1000950368_1:
  expose: false
light.sonoff_1000950368_1:
  expose: false
switch.sonoff_1000950368_2:
  expose: false
light.sonoff_1000950368_2:
  expose: false

# Living
light.living:
  name: "Luz del techo living"
  aliases:
    - "Luz"
    - "Lámpara de techo"
    - "Luz del living"
    - "Luz principal"
  room: Living

light.sonoff_1000766c93:
  name: "Lámpara de pie"
  aliases:
    - "Lámpara living"
    - "Lámpara pie"
    - "Luz secundaria"
  room: Living

climate.living_ac:
  name: "Aire acondicionado Living"
  aliases:
    - "Living"
    - "Aire"
    - "Aire acondicionado"
  room: Living

media_player.living_tv:
  name: "Televisión living"
  aliases:
    - "Living"
    - "Teve living"
    - "Tele living"
  room: Living

vacuum.vacuum:
  name: Aspiradora
  room: Living

# Kitchen
light.sonoff_100094ff53_1:
  name: "Luz principal"
  aliases:
    - "Cocina"
    - "Luz cocina"
    - "Luz principal"
  room: Cocina

light.sonoff_100094ff53_2:
  name: "Luz secundaria"
  room: Cocina

switch.sonoff_10008508fb:
  name: "Termotanque"
  room: Cocina

input_boolean.wb_auto_trigger:
  name: "Corte automático"
  aliases:
    - "Auto trigger"
  room: Cocina

sensor.cocina_temperatura:
  name: "Cocina"
  aliases:
    - "Temperatura cocina"
  room: Cocina

sensor.termotanque_temperatura:
  name: "Termotanque"
  aliases:
    - "Temperatura termotanque"
  room: Cocina

# Bedroom
light.bedroom:
  name: "Luz del dormitorio"
  aliases:
    - "Dormitorio"
    - "Luz del techo"
    - "Luz principal"
  room: Dormitorio

light.sonoff_1000770cc7:
  name: "Mesa de luz"
  aliases:
    - "Lámpara dormitorio"
  room: Dormitorio

climate.dormitorio_ac:
  name: "Aire dormitorio"
  aliases:
    - "Dormitorio"
    - "Aire pieza"
    - "Aire acondicionado"
    - "Aire acondicionado pieza"
  room: Dormitorio

fan.sonoff_1000954850:
  name: "Ventilador"
  aliases:
    - "Dormitorio"
    - "Ventilador pieza"
  room: Dormitorio

media_player.bedroom_tv:
  name: "Televisión dormitorio"
  aliases:
    - "Dormitorio"
    - "Televisión pieza"
    - "Teve dormitorio"
    - "Teve pieza"
    - "Tele dormitorio"
    - "Tele pieza"
  room: Dormitorio

# WC
light.sonoff_1000951aac:
  name: "Luz del baño"
  aliases:
    - "Baño"
  room: WC

# Stockroom
light.sonoff_1000951b70:
  name: "Luz depósito"
  aliases:
    - "Depósito"
  room: Stockroom

switch.sonoff_100085069c:
  name: "Aire depósito"
  aliases:
    - "Depósito"
    - "Aire acondicionado depósito"
  room: Stockroom

sensor.deposito_temperatura:
  name: "Depósito"
  aliases:
    - "Temperatura depósito"
  room: Stockroom

# Misc
switch.sonoff_100076dd3e:
  expose: false
light.outdoor:
  name: "Exterior"
  aliases:
    - "Luz exterior"
  room: Outside

light.sonoff_10008504ad:
  name: "Luz pasillo"
  aliases:
    - "Pasillo"
  room: Hallway

# Others
switch.pihole_google_entity:
  name: "Pihole"
  room: Others
