home_view:
  options:
    - lights
    - ac
    - plugs
  initial: lights

cal_view:
  options:
    - weather
    - aleph
  initial: weather

ac_location:
  name: AC Location
  options:
    - Living
    - Dormitorio
    - Stockroom
  initial: Living
  icon: mdi:air-conditioner

tv_location:
  options:
    - Living
    - Bedroom
  initial: Living
  icon: mdi:television-classic

media_view:
  options:
    - tv
    - tv_favs
    - tv_numeric
    - radio
  initial: tv

radio_station:
  name: 'Select Radio Station:'
  options:
    - Rivadavia
    - Mitre
    - CNN Argentina
    - Radio 10
    - BBC World News
  icon: mdi:radio

speakers:
  name: 'Select Speakers:'
  options:
    - Living
    - Chromecast
    - Kitchen
    - Bedroom
    - Everywhere
  initial: Kitchen
  icon: mdi:speaker-wireless

hue_living:
  options:
    - sunset
    - reading
    - white
    - calm

hue_hallway:
  options:
    - white
    - sunset

hue_bedroom:
  options:
    - calm
    - sunset
    - white

hue_table_lamp:
  options:
    - reading
    - sunset
    - calm

hue_wc:
  options:
    - white
    - sunset

theme:
  options:
    - blue-red
    - dark-blue
    - dark-green
    - light-blue
    - light-green
    - orange
    - red
  icon: mdi:format-color-fill
