blank:
  icon: 'mdi:'

blank_chart:
  icon: 'mdi:chart-line'

wb_auto_trigger:
  name: Auto trigger
  initial: on

pending_kiddush_levanah:
  name: Pending Kiddush Levanah
  icon: mdi:moon-waning-gibbous

ac_office_auto_trigger:
  name: Auto trigger
  initial: on

ac_melacha_auto_trigger:
  name: Auto trigger (melacha on)
  initial: on
