volume_speaker:
  name: Volume
  icon: mdi:volume-high
  min: 0
  max: 1
  step: 0.05
  initial: 0.45

fan_bedroom:
  name: Fan
  icon: mdi:fan
  min: 0
  max: 3
  step: 1
  initial: 0

hue_living1:
  min: 0
  max: 5
  step: 1
  initial: 0

hue_living2:
  min: 0
  max: 5
  step: 1
  initial: 0
