blank:
  icon: 'mdi:'

blank_chart:
  icon: 'mdi:chart-line'

wb_ignore_trigger:
  name: Ignore auto trigger
  initial: off

wb_ignore_melaja:
  name: Ignore melaja sensor
  initial: off

pending_kiddush_levanah:
  name: Pending Kiddush Levanah
  icon: mdi:moon-waning-gibbous
