hue:
  variables:
    name: >
      {% if name == "living" %} 1
      {% elif name == "bedroom" %} 2
      {% elif name == "hallway" %} 3
      {% elif name == "tablelamp" %} 4
      {% elif name == "wc" %} 5
      {% endif %}
    payload: >
      {% if mode == "reading" %} { "on": true, "bri": 254, "hue": 41442, "sat": 75, "xy": [ 0.445, 0.4067 ], "ct": 346 }
      {% elif mode == "white" %} { "on": true, "bri": 254, "hue": 41442, "sat": 75, "xy":  [ 0.3146, 0.3303 ], "ct": 156 }
      {% elif mode == "calm" %} { "on": true, "bri": 77, "hue": 8402, "sat": 140, "xy": [ 0.4575, 0.4099 ], "ct": 366 }
      {% elif mode == "sunset" %} { "on": true, "bri": 144, "hue": 7676, "sat": 199, "xy": [ 0.5016, 0.4151 ], "ct": 443 }
      {% elif mode == "night" %} { "on": true, "bri": 1, "hue": 6290, "sat": 251, "xy": [ 0.5612, 0.4042 ] }
      {% elif mode == "bri_inc" %} { "bri_inc": 30 }
      {% elif mode == "bri_dec" %} { "bri_inc": -30 }
      {% elif mode == "off" %} { "on": false }
      {% endif %}
  sequence:
    service: rest_command.hue
    data_template:
      resource: "{{ resource | default('groups', true) }}"
      name: "{{ name }}"
      payload: "{{ payload }}"

hue_dimmer:
  sequence:
      service: notify.file
      data_template:
        message: "name: {{ name }}, button: {{ button }}"

hue_palmbeach:
  sequence:
    - service: rest_command.hue
      data:
        resource: lights
        name: 1
        payload: '{ "on": true, "bri": 53, "hue": 36970, "sat": 242, "xy": [ 0.1715, 0.3561 ], "ct": 153 }'
    - service: rest_command.hue
      data:
        resource: lights
        name: 2
        payload: '{ "on": true, "bri": 69, "hue": 10984, "sat": 228, "xy": [ 0.4588, 0.4662 ], "ct": 366 }'
    - service: rest_command.hue
      data:
        resource: lights
        name: 3
        payload: '{ "on": true, "bri": 53, "hue": 61079, "sat": 119, "xy": [ 0.4652, 0.3152 ], "ct": 379 }'
    - service: rest_command.hue
      data:
        resource: lights
        name: 6
        payload: '{ "on": true, "bri": 53, "hue": 48749, "sat": 199, "xy": [ 0.24, 0.1371 ], "ct": 153 }'

turn_off_but_outside:
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.turn_off_but_outside
    - service: script.hue
      data:
        name: living
        mode: night
    - service: script.hue
      data:
        name: hallway
        mode: night
    - service: script.hue
      data:
        name: wc
        mode: night
    - service: script.hue
      data:
        name: tablelamp
        mode: night

broadlink_send_command:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command: >
          b64:{{ state_attr('sensor.broadlink_codes', device)[command] }}
        num_repeats: >
          {% if num_repeats %} {{ num_repeats }} {% else %} 1 {% endif %}

broadlink_fav_america:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['9'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['ok'] }}
        delay_secs: 0.5

broadlink_fav_canal9:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['1'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['3'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['ok'] }}
        delay_secs: 0.5

broadlink_fav_a24:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['1'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['5'] }}
        delay_secs: 0.5

broadlink_fav_volver:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['4'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['3'] }}
        delay_secs: 0.5

radio_station:
  sequence:
    - service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state('input_select.speakers', 'Living') %} media_player.living
          {% elif is_state('input_select.speakers', 'Chromecast') %} media_player.chromecast
          {% elif is_state('input_select.speakers', 'Kitchen') %} media_player.cocina
          {% elif is_state('input_select.speakers', 'Bedroom') %} media_player.dormitorio
          {% elif is_state('input_select.speakers', 'Everywhere') %} group.everywhere_speakers
          {% endif %}
        volume_level: "{{ states('input_number.volume_speaker')  }}"
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state('input_select.speakers', 'Living') %} media_player.living
          {% elif is_state('input_select.speakers', 'Chromecast') %} media_player.chromecast
          {% elif is_state('input_select.speakers', 'Kitchen') %} media_player.cocina
          {% elif is_state('input_select.speakers', 'Bedroom') %} media_player.dormitorio
          {% elif is_state('input_select.speakers', 'Everywhere') %} group.everywhere_speakers
          {% endif %}
        media_content_id: >
          {% if is_state('input_select.radio_station', 'Rivadavia') %} https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac
          {% elif is_state('input_select.radio_station', 'Mitre') %} http://buecrplb01.cienradios.com.ar/Mitre790.aac
          {% elif is_state('input_select.radio_station', 'CNN Argentina') %} http://estudio.cnnradioargentina.com.ar:8000/stream
          {% elif is_state('input_select.radio_station', 'Radio 10') %} https://s6.stweb.tv/radio10/live/playlist.m3u8
          {% elif is_state('input_select.radio_station', 'BBC World News') %} http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-einws
          {% endif %}
        media_content_type: 'audio/mp4'

stop_speaker:
  sequence:
    - service: media_player.media_stop
      data_template:
        entity_id: >
          {% if is_state('input_select.speakers', 'Living') %} media_player.living
          {% elif is_state('input_select.speakers', 'Chromecast') %} media_player.chromecast
          {% elif is_state('input_select.speakers', 'Kitchen') %} media_player.cocina
          {% elif is_state('input_select.speakers', 'Bedroom') %} media_player.dormitorio
          {% elif is_state('input_select.speakers', 'Everywhere') %} group.everywhere_speakers
          {% endif %}
