turn_off_but_outside:
  sequence:
    - service: light.turn_off
      data:
        entity_id: group.turn_off_but_outside

broadlink_send_command:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command: >
          b64:{{ state_attr('sensor.broadlink_codes', device)[command] }}
        num_repeats: >
          {% if num_repeats %} {{ num_repeats }} {% else %} 1 {% endif %}

broadlink_fav_america:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['9'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['ok'] }}
        delay_secs: 0.5

broadlink_fav_canal9:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['1'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['3'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['ok'] }}
        delay_secs: 0.5

broadlink_fav_a24:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['1'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['5'] }}
        delay_secs: 0.5

broadlink_fav_volver:
  sequence:
    - service: remote.send_command
      data_template:
        entity_id: >
          {% if is_state('input_select.tv_location', 'Living') %} remote.living_remote
          {% else %} remote.bedroom_remote
          {% endif %}
        command:
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['4'] }}
          - b64:{{ state_attr('sensor.broadlink_codes', 'television')['3'] }}
        delay_secs: 0.5

radio_station:
  sequence:
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state('input_select.speakers', 'Living') %} media_player.living
          {% elif is_state('input_select.speakers', 'Chromecast') %} media_player.chromecast
          {% elif is_state('input_select.speakers', 'Kitchen') %} media_player.cocina
          {% elif is_state('input_select.speakers', 'Bedroom') %} media_player.dormitorio
          {% elif is_state('input_select.speakers', 'Everywhere') %} group.everywhere_speakers
          {% endif %}
        media_content_id: >
          {% if is_state('input_select.radio_station', 'Rivadavia') %} https://playerservices.streamtheworld.com/api/livestream-redirect/RIVADAVIAAAC.aac
          {% elif is_state('input_select.radio_station', 'Mitre') %} http://buecrplb01.cienradios.com.ar/Mitre790.aac
          {% elif is_state('input_select.radio_station', 'CNN Argentina') %} http://estudio.cnnradioargentina.com.ar:8000/stream
          {% elif is_state('input_select.radio_station', 'Radio 10') %} https://s6.stweb.tv/radio10/live/playlist.m3u8
          {% elif is_state('input_select.radio_station', 'BBC World News') %} http://bbcwssc.ic.llnwd.net/stream/bbcwssc_mp1_ws-einws
          {% endif %}
        media_content_type: 'audio/mp4'

stop_speaker:
  sequence:
    - service: media_player.media_stop
      data_template:
        entity_id: >
          {% if is_state('input_select.speakers', 'Living') %} media_player.living
          {% elif is_state('input_select.speakers', 'Chromecast') %} media_player.chromecast
          {% elif is_state('input_select.speakers', 'Kitchen') %} media_player.cocina
          {% elif is_state('input_select.speakers', 'Bedroom') %} media_player.dormitorio
          {% elif is_state('input_select.speakers', 'Everywhere') %} group.everywhere_speakers
          {% endif %}
