# https://community.home-assistant.io/t/set-day-or-night-volume-to-speaker/294217
blueprint:
  name: Set volume of speakers based of time of day
  description: Set volume to different level on different times a day 
  domain: automation
  input:
    daytime_starts:
      name: Time of day
      description: Change level depending of time of day, Daytime level
      default: '07:00:00'
      selector:
        time:
    daytime_ends:
      name: Time of night
      description: Change level depending of time of day, Nighttime level
      default: '20:00:00'
      selector:
        time:
    volume_day:
      name: Set volume day
      description: The volume you want your media player to be reset to
      default: '0.5'
      selector:
        number:
          min: '0'
          max: '1'
          step: '0.1'
          mode: slider
    volume_night:
      name: Set volume night
      description: The volume you want your media player to be reset to
      default: '0.1'
      selector:
        number:
          min: '0'
          max: '1'
          step: '0.1'
          mode: slider
    filter:
      name: Filter players
      description: Players not to be reset or not. Only
        entities are supported, devices must be expanded!
      default:
        entity_id: []
      selector:
        target:
          entity:
            domain: media_player
    include_exclude:
      name: Filter invert
      description: Turn off to reset choosen and on to choose all other
      default: true
      selector:
        boolean: {}
variables:
  filter: !input 'filter'
  player: >
    {% set result = namespace(player=[]) %}
    {% for state in states.media_player %}
      {% if include_exclude == 'true' %}
        {% if not state.state == 'playing' and not state.entity_id in filter.entity_id %}
          {% set result.player = result.player + [state.entity_id] %}
        {% endif %}
      {% else %}
        {% if state.state != 'playing' and state.entity_id in filter.entity_id %}
          {% set result.player = result.player + [state.entity_id] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {{result.player|join(",")}}
trigger:
- platform: time
  at: !input 'daytime_starts'
- platform: time
  at: !input 'daytime_ends'
action:
  - choose:
      - conditions:
          - after: !input 'daytime_starts'
            before: !input 'daytime_ends'
            condition: time
        sequence:  
          - service: media_player.volume_set
            data_template:
              entity_id: '{{ player }}'
              volume_level: !input 'volume_day'
    default:
      - service: media_player.volume_set
        data_template:
          entity_id: '{{ player }}'
          volume_level: !input 'volume_night'
mode: 'single'
