---

- alias: Turn on condensate pump
  trigger:
    - platform: state
      entity_id: climate.living_ac
      to:
        - 'cool'
        - 'heat'
        - 'dry'
    - platform: state
      entity_id: climate.dormitorio_ac
      to:
        - 'cool'
        - 'heat'
        - 'heat_cool'
        - 'dry'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_1000854c6a

- alias: Turn off condensate pump living
  trigger:
    - platform: state
      entity_id: climate.living_ac
      to: 'off'
    - platform: state
      entity_id: climate.dormitorio_ac
      to: 'off'
  condition:
    - condition: state
      entity_id: climate.dormitorio_ac
      state: 'off'
    - condition: state
      entity_id: climate.living_ac
      state: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.sonoff_1000854c6a

- alias: Turn on office's AC
  trigger:
    platform: time
    at: '08:30:00'
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.ac_office_auto_trigger
      state: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.sonoff_100085069c

- alias: From wall switch turn on office's AC
  trigger:
    platform: state
    entity_id: switch.sonoff_1000950368_2
    to: 'on'
  condition:
    condition: state
    entity_id: switch.sonoff_100085069c
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_100085069c

- alias: From wall switch turn off office's AC
  trigger:
    platform: state
    entity_id: switch.sonoff_1000950368_2
    to: 'off'
  condition:
    condition: state
    entity_id: switch.sonoff_100085069c
    state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.sonoff_100085069c

- alias: From office's AC sync to wall switch to on
  trigger:
    platform: state
    entity_id: switch.sonoff_100085069c
    to: 'on'
  condition:
    condition: state
    entity_id: switch.sonoff_1000950368_2
    state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_1000950368_2

- alias: From office's AC sync to wall switch to off
  trigger:
    platform: state
    entity_id: switch.sonoff_100085069c
    to: 'off'
  condition:
    condition: state
    entity_id: switch.sonoff_1000950368_2
    state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.sonoff_1000950368_2

- alias: Turn on AC Living
  trigger:
    - platform: time
      at: '09:00:00'
    - platform: time
      at: '15:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.living_ac
      data:
        temperature: 22
        hvac_mode: cool
    - service: climate.set_fan_mode
      target:
        entity_id: climate.living_ac
      data:
        fan_mode: level3
    - service: climate.turn_off
      target:
        entity_id: climate.dormitorio_ac

- alias: Turn off AC Living
  trigger:
    - platform: time
      at: '11:00:00'
    - platform: time
      at: '18:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    service: climate.turn_off
    target:
      entity_id: climate.living_ac

- alias: Turn on AC bedroom
  trigger:
    - platform: time
      at: '15:00:00'
    - platform: time
      at: '23:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    - service: climate.set_temperature
      target:
        entity_id: climate.dormitorio_ac
      data:
        temperature: 24
        hvac_mode: cool
    - service: climate.set_fan_mode
      target:
        entity_id: climate.dormitorio_ac
      data:
        fan_mode: med
    - service: climate.turn_off
      target:
        entity_id: climate.living_ac

- alias: Turn off AC Bedroom
  trigger:
    - platform: time
      at: '09:00:00'
    - platform: time
      at: '18:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    service: climate.turn_off
    target:
      entity_id: climate.dormitorio_ac
