---

- alias: Reuse Hue switch to turn on table lamp
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: table_lamp_button
        type: initial_press
        subtype: 1
    - platform: event
      event_type: hue_event
      event_data:
        id: table_lamp_button
        type: initial_press
        subtype: 4
  action:
    choose:
      conditions:
        condition: template
        value_template: "{{ trigger.event.data.subtype == 1 }}"
      sequence:
        service: light.turn_on
        entity_id: light.table_lamp
    default:
      service: light.turn_off
      entity_id: light.table_lamp

- alias: Hue switch
  trigger:
    - platform: event
      event_type: hue_event
      event_data:
        id: living_1_button
    - platform: event
      event_type: hue_event
      event_data:
        id: living_2_button
    - platform: event
      event_type: hue_event
      event_data:
        id: hallway_button
    - platform: event
      event_type: hue_event
      event_data:
        id: bedroom_button
    - platform: event
      event_type: hue_event
      event_data:
        id: wc_button
  variables:
    zone: "{{ trigger.event.data.id | regex_replace('_.*', '') }}"
    type: "{{ trigger.event.data.type }}"
    button: "{{ trigger.event.data.subtype }}"
    light: "light.{{ zone }}"
    bri: "{{ state_attr(light, 'brightness') }}"
  condition:
    condition: template
    value_template: "{{ not type | regex_match('.*_release') }}"
  action:
    choose:
      - alias: Turn on night mode
        conditions:
          - "{{ button == 1 }}"
          - condition: template
            value_template: "{{ states(light) == 'off' }}"
          - condition: time
            before: "07:00:00"
        sequence:
          service: hue.hue_activate_scene
          data:
            group_name: "{{ zone }}"
            scene_name: "Luz nocturna"
      - alias: Turn on
        conditions:
          - "{{ button == 1 }}"
          - "{{ type != 'repeat' }}"
        sequence:
          service: hue.hue_activate_scene
          data:
            group_name: "{{ zone }}"
            scene_name: >
              {% if bri == None or bri <= 75 or bri == 255 %} Atenuada
              {% else %} Luminosa
              {% endif %}
      - alias: Turn on night mode on press
        conditions:
          - "{{ button == 1 }}"
          - "{{ type == 'repeat' }}"
        sequence:
          service: hue.hue_activate_scene
          data:
            group_name: "{{ zone }}"
            scene_name: "Luz nocturna"
      - alias: Increase brightness
        conditions:
          - "{{ button == 2 }}"
          - "{{ states(light) == 'on' }}"
        sequence:
          service: light.turn_on
          data_template:
            entity_id: "{{ light }}"
            brightness_step: 85
      - alias: Decrease brightness
        conditions:
          - "{{ button == 3 }}"
          - "{{ states(light) == 'on' }}"
        sequence:
          service: light.turn_on
          data_template:
            entity_id: "{{ light }}"
            brightness: >
              {% if bri >= 86 %} {{ bri - 85 }}
              {% else %} 1
              {% endif %}
      - alias: Turn off
        conditions: "{{ button == 4 }}"
        sequence:
          service: light.turn_off
          data_template:
            entity_id: "{{ light }}"
