---

- alias: Sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: light.turn_off
    entity_id:
      - light.outdoor
      - light.living
      - light.hallway
      - light.wc

- alias: Avoid Sunrise when Melacha is on
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'off'
  action:
    service: light.turn_off
    entity_id: light.table_lamp

- alias: Sunset
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    - service: light.turn_on
      entity_id:
        - light.outdoor
        - light.table_lamp
    - service: hue.hue_activate_scene
      data:
        group_name: hallway
        scene_name: Relax

- alias: Midnight
  trigger:
    platform: time
    at: '00:00:00'
  condition:
    condition: state
    entity_id: input_boolean.turn_off_but_outside
    state: 'on'
  action:
    service: script.turn_off_but_outside

- alias: Toggle floor lamp
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      name: floorlamp
  action:
    service: light.toggle
    entity_id: light.floor_lamp

- alias: Toggle kitchen light01
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      name: Kitchen_Button1
  action:
    service: light.toggle
    entity_id: light.kitchen_1st

- alias: Toggle kitchen light02
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      name: Kitchen_Button2
  action:
    service: light.toggle
    entity_id: light.kitchen_2nd

- alias: Turn on lights at Shabbatot
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: living
        scene_name: Luminosa
    - service: hue.hue_activate_scene
      data:
        group_name: hallway
        scene_name: Luminosa
    - service: hue.hue_activate_scene
      data:
        group_name: bedroom
        scene_name: Luminosa
    - service: hue.hue_activate_scene
      data:
        group_name: wc
        scene_name: Luminosa
    - service: light.turn_on
      entity_id: light.kitchen_2nd
    - service: light.turn_off
      entity_id: light.floor_lamp

- alias: Turn off lights on Shabbatot at night
  trigger:
    platform: time
    at: '00:30:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.bedroom
        - light.kitchen_2nd
    - service: hue.hue_activate_scene
      data:
        group_name: living
        scene_name: "Luz nocturna"
    - service: hue.hue_activate_scene
      data:
        group_name: hallway
        scene_name: "Luz nocturna"
    - service: hue.hue_activate_scene
      data:
        group_name: wc
        scene_name: "Luz nocturna"

- alias: Turn on lights on Shabbatot at morning
  trigger:
    platform: time
    at: '09:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    - service: hue.hue_activate_scene
      data:
        group_name: living
        scene_name: Luminosa
    - service: hue.hue_activate_scene
      data:
        group_name: hallway
        scene_name: Luminosa
    - service: hue.hue_activate_scene
      data:
        group_name: wc
        scene_name: Luminosa
    - service: light.turn_on
      entity_id: light.kitchen_2nd
