---

# Google Sync
- alias: Sync Google Assistant
  trigger:
    platform: homeassistant
    event: start
  action:
    - delay: '00:00:45'
    - service: google_assistant.request_sync

# PiHole
- alias: Enable Pihole again
  trigger:
    - platform: state
      entity_id: sensor.pihole_status
      to: 'Enabled'
  condition:
    - condition: state
      entity_id: switch.pihole
      state: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.pihole

# Calendar
- alias: Turn on pending Kiddush Levanah
  trigger:
    platform: state
    entity_id: sensor.moon
    to:
      - 'waxing_gibbous'
      - 'full_moon'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.pending_kiddush_levana

- alias: Turn off pending Kiddush Levanah
  trigger:
    platform: state
    entity_id: sensor.moon
    to: 'waning_gibbous'
  condition:
    - condition: state
      entity_id: input_boolean.pending_kiddush_levana
      state: 'on'
  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.pending_kiddush_levana

# Buzzer
- alias: Buzzer
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      name: buzzer
  action:
    service: notify.mobile_app_fbs_iphone
    data:
      message: "\uD83D\uDD14 Someone's at front door"

# Flood
- alias: Flood
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      name: flood_alert
  action:
    service: notify.mobile_app_fbs_iphone
    data:
      message: "\uD83D\uDCA7 Washing machine is leaking"

# Partition free space
- alias: Partition free space
  trigger:
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_var_log
      value_template: "{{ float(states('sensor.disk_use_percent_var_log')) }}"
      above: 70
    - platform: numeric_state
      entity_id: sensor.disk_use_percent_var_log
      value_template: "{{ float(states('sensor.disk_use_percent_var_log')) }}"
      above: 80
  variables:
    state: "{{ states('sensor.disk_use_percent_var_log') }}"
    level: "{% if float(state) >= 80 %}\uD83D\uDD34 CRITICAL{% else %}\uD83D\uDFE1 WARNING{% endif %}"
  action:
    - service: notify.mobile_app_fbs_iphone
      data:
        title: "{{ level }}"
        message: "Partition /var/log raised {{ state }}%"
    - service: notify.mobile_app_facundos_macbook_air
      data:
        title: "{{ level }}"
        message: "Partition /var/log raised {{ state }}%"
