---

- alias: Turn on plug for hot plate
  trigger:
    - platform: time
      at: '21:00:00'
    - platform: time
      at: '13:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    service: switch.turn_on
    target:
      entity_id: switch.ebd3e3a329b4054394h4ah

- alias: Turn off plug for hot plate
  trigger:
    - platform: time
      at: '23:00:00'
    - platform: time
      at: '15:00:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    service: switch.turn_off
    target:
      entity_id: switch.ebd3e3a329b4054394h4ah
