---

- alias: Turn on plug for hot plate
  trigger:
    - platform: time
      at: '20:00:00'
    - platform: time
      at: '12:30:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    service: switch.turn_on
    target:
      entity_id:
        - switch.plug_left
        - switch.plug_right

- alias: Turn off plug for hot plate
  trigger:
    - platform: time
      at: '23:00:00'
    - platform: time
      at: '15:30:00'
  condition:
    condition: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    state: 'on'
  action:
    service: switch.turn_off
    target:
      entity_id:
        - switch.plug_left
        - switch.plug_right

- alias: Turn off plug for hot plate - safe one
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'off'
  action:
    service: switch.turn_off
    target:
      entity_id:
        - switch.plug_left
        - switch.plug_right
