---

- alias: Turn on water boiler
  trigger:
    - platform: time
      at:
        - '06:00:00'
        - '17:00:00'
    - platform: state
      entity_id: input_boolean.wb_auto_trigger
      to: 'off'
    - platform: template
      value_template: "{{ as_timestamp(now()) >= (as_timestamp(states('sensor.jewish_calendar_upcoming_candle_lighting')) - 170 * 60) }}"
  action:
    service: switch.turn_on
    entity_id: switch.sonoff_10008508fb

- alias: Turn off water boiler
  trigger:
    - platform: numeric_state
      entity_id: sensor.termotanque_temperatura
      above: 62
    - platform: state
      entity_id: switch.sonoff_10008508fb
      to: 'on'
    - platform: state
      entity_id: input_boolean.wb_auto_trigger
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.termotanque_temperatura
      above: 62
    - condition: state
      entity_id: input_boolean.wb_auto_trigger
      state: 'on'
  action:
    service: switch.turn_off
    entity_id: switch.sonoff_10008508fb

- alias: Toggle water boiler
  trigger:
    platform: event
    event_type: sonoff.remote
    event_data:
      name: wb
  action:
    service: switch.toggle
    entity_id: switch.sonoff_10008508fb
