- platform: group
  name: Living
  entities:
    - light.hue_color_lamp_1
    - light.hue_color_lamp_2
    - light.hue_color_lamp_3
    - light.hue_color_lamp_4
    - light.hue_color_lamp_5_3
    - light.hue_color_lamp_6

- platform: group
  name: Bedroom
  entities:
    - light.hue_color_lamp_7
    - light.hue_color_lamp_8

- platform: group
  name: WC
  entities:
    - light.hue_color_spot_1
    - light.hue_color_spot_3

- platform: switch
  name: Outdoor
  entity_id: switch.sonoff_100076dd3e

- platform: switch
  name: Table lamp
  entity_id: switch.sonoff_1000770cc7

- platform: switch
  name: Floor lamp
  entity_id: switch.sonoff_1000766c93

- platform: switch
  name: Kitchen 1st
  entity_id: switch.sonoff_100094ff53_1

- platform: switch
  name: Kitchen 2nd
  entity_id: switch.sonoff_100094ff53_2

- platform: switch
  name: Office
  entity_id: switch.sonoff_1000950368_1
