- platform: template
  switches:

    pihole_google_entity:
      value_template: "{{ is_state('sensor.pihole_status', 'Enabled') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.pihole_google_entity
      turn_off:
        service: pi_hole.disable
        data:
          entity_id: switch.pihole
          duration: '00:00:30'

    media_player_speaker:
      friendly_name: "Connect"
      value_template: >
        {% if is_state('input_select.speakers', 'Living') %} {% set player = 'media_player.living' %}
        {% elif is_state('input_select.speakers', 'Chromecast') %} {% set player = 'media_player.chromecast' %}
        {% elif is_state('input_select.speakers', 'Kitchen') %} {% set player = 'media_player.cocina' %}
        {% elif is_state('input_select.speakers', 'Bedroom') %} {% set player = 'media_player.dormitorio' %}
        {% else %} {% set player = 'group.everywhere_speakers' %}
        {% endif %}
        {{ states(player) in ['on', 'playing', 'idle'] }}
      turn_on:
        service: media_player.turn_on
        data_template:
          entity_id: >
            {% if is_state('input_select.speakers', 'Living') %} media_player.living
            {% elif is_state('input_select.speakers', 'Chromecast') %} media_player.chromecast
            {% elif is_state('input_select.speakers', 'Kitchen') %} media_player.cocina
            {% elif is_state('input_select.speakers', 'Bedroom') %} media_player.dormitorio
            {% else %} group.everywhere_speakers
            {% endif %}
      turn_off:
        service: media_player.turn_off
        data_template:
          entity_id: >
            {% if is_state('input_select.speakers', 'Living') %} media_player.living
            {% elif is_state('input_select.speakers', 'Chromecast') %} media_player.chromecast
            {% elif is_state('input_select.speakers', 'Kitchen') %} media_player.cocina
            {% elif is_state('input_select.speakers', 'Bedroom') %} media_player.dormitorio
            {% else %} group.everywhere_speakers
            {% endif %}
      icon_template: >
        {% if is_state('input_select.speakers', 'Living') %} {% set player = 'media_player.living' %}
        {% elif is_state('input_select.speakers', 'Chromecast') %} {% set player = 'media_player.chromecast' %}
        {% elif is_state('input_select.speakers', 'Kitchen') %} {% set player = 'media_player.cocina' %}
        {% elif is_state('input_select.speakers', 'Bedroom') %} {% set player = 'media_player.dormitorio' %}
        {% else %} {% set player = 'group.everywhere_speakers' %}
        {% endif %}
        {% if states(player) in ['on', 'playing', 'idle'] %} mdi:toggle-switch
        {% else %} mdi:toggle-switch-off-outline
        {% endif %}

    climate_living:
      friendly_name: Living
      icon_template: mdi:air-conditioner
      value_template: "{{ not is_state('climate.living_ac', 'off') }}"
      turn_on:
        service: climate.turn_on
        entity_id: climate.living_ac
      turn_off:
        service: climate.turn_off
        entity_id: climate.living_ac

    climate_bedroom:
      friendly_name: Bedroom
      icon_template: mdi:air-conditioner
      value_template: "{{ not is_state('climate.dormitorio_ac', 'off') }}"
      turn_on:
        service: climate.turn_on
        entity_id: climate.dormitorio_ac
      turn_off:
        service: climate.turn_off
        entity_id: climate.dormitorio_ac

    climate_office:
      friendly_name: Office
      icon_template: mdi:air-conditioner
      value_template: "{{ states('switch.sonoff_100085069c') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.sonoff_100085069c
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.sonoff_100085069c

    plug_left:
      friendly_name: Plug at left
      icon_template: mdi:power-socket-au
      value_template: "{{ states('switch.ebd3e3a329b4054394h4ah') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.ebd3e3a329b4054394h4ah
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.ebd3e3a329b4054394h4ah

    plug_right:
      friendly_name: Plug at right
      icon_template: mdi:power-socket-au
      value_template: "{{ states('switch.160505002cf432c53e7b') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.160505002cf432c53e7b
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.160505002cf432c53e7b
